# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.67083006 0.69984178 0.74350006 ... 0.46320657 0.77549086 0.6904627 ]
 [0.33082069 0.48831525 0.51573652 ... 0.1916063  0.06350972 0.98741887]
 [0.72907621 0.69547913 0.42481397 ... 0.04012849 0.48894111 0.83842709]
 ...
 [0.91869511 0.74745753 0.46154433 ... 0.1816459  0.01545488 0.44133212]
 [0.41421744 0.74910007 0.36852038 ... 0.28843038 0.71593405 0.18488824]
 [0.87585937 0.67884955 0.38277312 ... 0.7191967  0.50652994 0.95492386]]
[[0.35716078 0.00992578 0.45973106 ... 0.40863134 0.35109628 0.97142081]
 [0.35949769 0.02558205 0.74679538 ... 0.92202065 0.45437301 0.735323  ]
 [0.02713731 0.0211653  0.9614223  ... 0.88714565 0.48564314 0.32162018]
 ...
 [0.29602241 0.71447324 0.52184641 ... 0.32621522 0.27205714 0.72669409]
 [0.54347832 0.25844911 0.8735757  ... 0.01314369 0.05684312 0.93932126]
 [0.6164132  0.44819888 0.13565063 ... 0.81828769 0.06288387 0.43013804]]


Без использования numpy

In [4]:
def mult(a, b):
    result = None
    rows_a = len(a)
    cols_a = len(a[0])
    rows_b = len(b)
    cols_b = len(b[0])

    # Проверка равенства столбцов
    if cols_a != rows_b:
        raise print("Количество столбцов в первой матрице должно быть равно количеству строк во второй")

    # Создаем результирующую матрицу с нулями
    result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]

    # Перемножаем матрицы
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [5]:
def np_mult(a, b):
    result = None
    result = np.dot(a, b)
    return result

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 726 ms, sys: 6.27 ms, total: 732 ms
Wall time: 734 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 957 µs, sys: 42 µs, total: 999 µs
Wall time: 5.21 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5560885913146194e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.9104781  0.22809151 0.32460228] [0.89471377 0.7265385  0.51416062]


In [10]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [11]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [12]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 29 µs, sys: 0 ns, total: 29 µs
Wall time: 32.9 µs
CPU times: user 194 µs, sys: 0 ns, total: 194 µs
Wall time: 1.03 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy быстрее благодаря оптимизациям на уровне C, векторизации операций и эффективному управлению памятью, что позволяет обрабатывать большие массивы данных более эффективно.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [13]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  # Извлечение диагональных элементов
  diag_elements = np.diag(a)
  # Фильтрация четных элементов
  even_elements = diag_elements[diag_elements % 2 == 0]
  # Суммирование четных элементов
  res = even_elements.sum()
  return res

In [14]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 6, 8, 8, 4],
       [6, 9, 2, 4, 9],
       [3, 6, 4, 2, 2],
       [9, 8, 8, 4, 7],
       [4, 3, 6, 2, 1]])

In [15]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 214 µs, sys: 0 ns, total: 214 µs
Wall time: 223 µs


8

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [21]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    # Извлечение массива из кортежа
    A = A[0]
    # Проверка размерности массива и преобразование в двумерный при необходимости
    if A.ndim == 1:
        A = A.reshape(1, -1)
    # Вычисление кумулятивной суммы вдоль строк
    cum_sum = np.cumsum(A, axis=1)
    # Получение количества элементов для деления
    divisors = np.arange(1, A.shape[1] + 1)
    # Вычисление средних значений
    result = cum_sum / divisors
    return result

In [22]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.0393604  0.94715999 0.55140468 0.54539412 0.91498194 0.64339121
 0.4716884  0.07923003 0.04502734 0.08918376 0.04510502 0.43450386
 0.26850707 0.87267251 0.21294112 0.72963621 0.16222978 0.02086663
 0.43582196 0.31228886 0.16291032 0.00233358 0.60055647 0.20137772
 0.48464022 0.69310919 0.49514646 0.44766665 0.10528183 0.5362396
 0.99132869 0.1234992  0.20468783 0.07280524 0.33568026 0.52868447
 0.32102461 0.44866778 0.1546873  0.71291275 0.52725303 0.40711094
 0.3128228  0.75812254 0.80850431 0.72002867 0.34203934 0.16058602
 0.88567805 0.3253489  0.48203806 0.52493667 0.94012389 0.8828089
 0.80607582 0.05201728 0.69327096 0.28793192 0.76237826 0.76527862
 0.8111588  0.80548934 0.52349535 0.70847639 0.63245952 0.63532275
 0.99657572 0.42432219 0.24916546 0.29355285 0.93278469 0.65703951
 0.94026329 0.28734938 0.17092861 0.22280935 0.93140839 0.33523679
 0.79400653 0.00826349 0.3579297  0.44792056 0.43732265 0.98772043
 0.43927506 0.57257544 0.49132198 0.57181776 0.54481944 0.395504

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [23]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    # Находим индексы, где значение изменяется
    change_indices = np.where(np.diff(a, prepend=a[0]-1, append=a[-1]+1) != 0)[0]
    # Элементы - это значения в индексах изменений
    elements = a[change_indices[:-1]]
    # Частоты - разница между последовательными индексами изменений
    frequencies = np.diff(change_indices)
    result = (elements, frequencies)
    return result

In [24]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 271 µs, sys: 35 µs, total: 306 µs
Wall time: 317 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [25]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    # Создаем копию массива X
    Y = copy(X)
    # Замена элементов с нечетными индексами на число a
    Y[1::2] = a
    # Возведение элементов с четными индексами в куб
    Y[::2] = np.power(Y[::2], 3)
    # Переворачиваем массив Y
    Y = Y[::-1]
    # Склеиваем X и Y, затем переворачиваем
    result = np.concatenate((X, Y))[::-1]
    return result

In [26]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 257 µs, sys: 0 ns, total: 257 µs
Wall time: 1.3 ms
